Models/Proveedores.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public int telefono { get; set; }
        public string direccion { get; set; }
    }
}

Controllers/ProveedoresController.cs
using Mvc6.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc6.Controllers
{
    public class ProveedoresController : Controller
    {
        public ActionResult Index()
        {
            using (NegocioEntities db = new NegocioEntities())
            {
                var UserEmail = Session["userEmail"] as string;

                var us = db.Usuarios.FirstOrDefault(e => e.email == UserEmail);

                if (us.rol == "ADM")
                {
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
        }

        public ActionResult GetData()
        {
            using (NegocioEntities db = new NegocioEntities())
            {
                List<Proveedores> provList = db.Proveedores.ToList<Proveedores>();
                List<Proveedores> provListFinal = new List<Proveedores>();

                foreach (Proveedores p in provList)
                {
                    Proveedores pFinal = new Proveedores();
                    pFinal.id = p.id;
                    pFinal.nombre = p.nombre;
                    pFinal.email = p.email;
                    pFinal.telefono = p.telefono;
                    pFinal.direccion = p.direccion;

                    provListFinal.Add(pFinal);
                }

                log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
                logger.Error("Error de sistema");

                return Json(new { data = provListFinal }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new Proveedores());
            else
            {
                using (NegocioEntities db = new NegocioEntities())
                {
                    return View(db.Proveedores.Where(x => x.id == id).FirstOrDefault<Proveedores>());
                }
            }
        }

        [HttpPost]
        public ActionResult AddOrEdit(Proveedores prov)
        {
            using (NegocioEntities db = new NegocioEntities())
            {
                if (prov.id == 0)
                {
                    prov.id = Convert.ToInt32(Convert.ToString(db.Proveedores.ToList().Last().id + 1));
                    db.Proveedores.Add(prov);
                    db.SaveChanges();
                    return Json(new { success = true, message = "Nuevo registro guardado exitosamente" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    db.Entry(prov).State = System.Data.EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = "Registro editado exitosamente" }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            using (NegocioEntities db = new NegocioEntities())
            {
                Proveedores prov = db.Proveedores.Where(x => x.id == id).FirstOrDefault<Proveedores>();
                db.Proveedores.Remove(prov);
                db.SaveChanges();
                return Json(new { success = true, message = "Registro eliminado exitosamente" }, JsonRequestBehavior.AllowGet);
            }
        }

        protected override void Dispose(bool disposing)
        {
            using (NegocioEntities db = new NegocioEntities())
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
        }
    }
}

Views/Proveedores/AddOrEdit.cshtml
@model Mvc6.Models.Proveedores

@{
    Layout = null;
}

@using (Html.BeginForm("AddOrEdit", "Proveedores", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
{
    @Html.HiddenFor(model => model.id)
    <br />
    <div class="form-group">
        @Html.LabelFor(model => model.nombre, new { @class = "control-label" })
        @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(model => model.email, new { @class = "control-label" })
        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(model => model.telefono, new { @class = "control-label" })
        @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(model => model.direccion, new { @class = "control-label" })
        @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <br />
    <div class="form-group">
        <input type="submit" value="Guardar" class="btn btn-primary" />
    </div>
}

Views/Proveedores/Index.cshtml
@model IEnumerable<Mvc6.Models.Proveedores>

@{
    ViewBag.Title = "Index";
}

<div style="display: flex; align-items: baseline;">
    <h2 style="color: forestgreen; font-family: Middle Schooler; font-size: 58px">ABM Proveedores</h2>&nbsp;&nbsp;&nbsp;
    <h2 style="color: orangered; font-family: MATILDAS BACK TO SCHOOL_Demo; font-size: 45px"> RC</h2>
</div>

<a class="btn btn-success" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("AddOrEdit","Proveedores")')"><i class="fa fa-plus"></i> Nuevo</a>

<table id="proveedoresTable" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Email</th>
            <th>Telefono</th>
            <th>Direccion</th>
            <th></th>
        </tr>
    </thead>
</table>

<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

@section scripts{
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>

    <script>
		var Popup, dataTable;

        $(document).ready(function () {

            dataTable = $("#proveedoresTable").DataTable({
                "bFilter": false,
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todo"]],
                "ajax": {
                    "url": "/Proveedores/GetData",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "nombre" },
                    { "data": "email" },
                    { "data": "telefono" },
                    { "data": "direccion" },
                    {
                        "data": "id", "render": function (data) {
                            return "<a class='btn btn-primary btn-sm' onclick=PopupForm('@Url.Action("AddOrEdit","Proveedores")/" + data + "')>Editar</a><a class='btn btn-danger btn-sm' style='margin-left:5px' onclick=Delete("+data+")>Borrar</a>";
                        },
                        "orderable": false,
                        "width": "150px"
                    }
                ],
                "language": {
                    "emptyTable" : "No hay proveedores registrados, click en <b>Add New</b> Button"
                }
            });
        });

        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
            .done(function (response) {
                formDiv.html(response);

                Popup = formDiv.dialog({
                    autoOpen: true,
                    resizable: false,
                    title: 'Crear o editar proveedor',
                    width: 'auto',
                    close: function(){
                        Popup.dialog('destroy').remove();
                    }
                });
            });
        }

        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {

                $.ajax({
                    type: "POST",
                    url: form.action,
                    data: $(form).serialize(),
                    success: function (data) {
                        if (data.success) {
                            Popup.dialog('close');
                            dataTable.ajax.reload();

                            $.notify(data.message,{
                                globalPosition : "top center",
                                className : "success"
                            })
                        }
                    }
                });
            }
            return false;
        }

        function Delete(id) {
            if (confirm('¿Seguro que desea eliminar este proveedor?'))
            {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete","Proveedores")/' + id,
                    success: function (data) {
                        if (data.success) {
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })
                        }
                    }
                });
            }
        }
    </script>
}